version: '3.1'
services:
  mongodb:
    image: mongo:latest
    container_name: $MONGO_CONTAINER_NAME
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    command: ["--bind_ip", "0.0.0.0"]
networks:
  main-network:
    external:
      name: $NETWORK_NAME